### PR TITLE
Increase scaled cost value range

### LINKED ISSUE #112: Track-to-detection scores of different values get mapped to the same cost values
### Summary

Track-to-detection scores with different values sometimes get mapped to the same cost value, making their association nondeterministic. In reality, these associations should be deterministic. This is an implementation issue with the library’s integration with Dlib. Here are some example scores:

```
1.40115 9.01495 99.1375 2.56529 9.76121 
96.9642 89.3636 6.31009 96.1101 88.6045 
2.34621 9.95255 100.079 3.39704 10.7028 
9.24669 1.82603 88.6573 8.26171  1.5591 
```

Here are their associated costs:

```
98 90  0 97 90 
 3 10 93  3 11 
97 90  0 96 89 
90 98 11 91 98 
 0  0  0  0  0 
```

### Commit

`develop`

### Expected Behavior

Unique score values translate to unique cost values

### Actual Behavior

Unique score values do not necessarily translate to unique cost values

### Steps to Reproduce the Actual Behavior

Observe example output from above

### Related Work

[CDAR-587](https://usdot-carma.atlassian.net/browse/CDAR-587)

[CDAR-587]: https://usdot-carma.atlassian.net/browse/CDAR-587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by adamlm**
# PR Details
## Description

This PR fixes a bug with track-to-detection cost matrix generation. When generating to cost matrix for track-to-detection scoring, the value range was only 0-100, causing some scores with different floating-point values to get mapped to the same integer value. The integer value range is now between 0-100,000,000.

## Related GitHub Issue

Closes #112 

## Related Jira Key

Closes [CDAR-587](https://usdot-carma.atlassian.net/browse/CDAR-587)

## Motivation and Context

Bug fix

## How Has This Been Tested?

Manually in downstream packages

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.

[CDAR-587]: https://usdot-carma.atlassian.net/browse/CDAR-587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: include/multiple_object_tracking/track_matching.hpp [hunk 1]
```diff
@@ -141,7 +141,7 @@ inline auto cost_matrix_from_score_matrix(const dlib::matrix<float> & score_matr
       const float cost_value = 1.0 - normalized_score;
 
       // Scale the cost value by multiplying it by 100 and convert it to an integer
```
Comment (paulbourelly999) [inline include/multiple_object_tracking/track_matching.hpp:143]: Fix the comment

**Review by paulbourelly999 — CHANGES_REQUESTED** [review]
Small questions

**Review by paulbourelly999 — APPROVED** [review]
