### PR TITLE
Fix making square matrix implementation

### LINKED ISSUE #106: Detection to track association function assigns uses wrong assignments
### Summary

The `multiple_object_tracking` library’s track-to-detection assignment step issues the wrong assignments in some circumstances. A known error-example is with the following track-to-detection scores:

| Track ID | Detection ID | Score   |
| -------- | ------------ | ------- |
| 0002-207 | 0002-207     | 6.43685 |
| 0002-207 | 0002-221     | 105.157 |

Track `0002-207` should get assigned to detection `0002-207` because it’s closer, but it gets assigned to detection `0002-221`.

### Commit

`develop`

### Expected Behavior

The track-to-detection step properly assigns the closest detection in all cases.

### Actual Behavior

The track-to-detection step properly assigns the furthest detection in some cases.

### Steps to Reproduce the Actual Behavior

1. Run the track-to-detection association step with the above scores

### Related Work

[CDAR-577](https://usdot-carma.atlassian.net/browse/CDAR-577)

[CDAR-577]: https://usdot-carma.atlassian.net/browse/CDAR-577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by adamlm**
# PR Details
## Description

This PR fixes an issue that caused incorrect track-to-detection associations for certain scenarios. There was some issue with the implementation for making cost matrices squared. Instead of using dlib::tmp, we are now explicitly creating a new empty matrix then populating the data manually. This operation was also moved into its own function. We can refine the implementation later if needed, but the separate function abstracts the current implementation.

## Related GitHub Issue

Closes #106 

## Related Jira Key

Closes [CDAR-577](https://usdot-carma.atlassian.net/browse/CDAR-577)

## How Has This Been Tested?

Unit tests

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)

## Checklist:

- [x] I have added any new packages to the sonar-scanner.properties file
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

[CDAR-577]: https://usdot-carma.atlassian.net/browse/CDAR-577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: include/multiple_object_tracking/detail/dlib_extensions.hpp [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+    for (auto column{0U}; column < matrix.nc(); ++column) {
+      square_matrix(row, column) = matrix(row, column);
+    }
+  }
+
+  for (auto row{matrix.nr()}; row < square_matrix_size; ++row) {
+    for (auto column{matrix.nc()}; column < square_matrix_size; ++column) {
+      square_matrix(row, column) = padding_value.value;
+    }
+  }
```
Comment (MishkaMN) [inline include/multiple_object_tracking/detail/dlib_extensions.hpp:35]: I could be wrong, but if column is higher for example, we should start padding from `row: matrix.nr()` which is correct. But the column should start from 0, not `matrix.nc()` right?

**Review by MishkaMN — CHANGES_REQUESTED** [review]

File: include/multiple_object_tracking/detail/dlib_extensions.hpp (hunk 1 above)
Comment (MishkaMN) [reply include/multiple_object_tracking/detail/dlib_extensions.hpp:35]: If the rows are higher, then row should start from 0, and columns should start from `matrix.nc()`

**Review by MishkaMN — APPROVED** [review]
