### PR TITLE
Wrap angle values when dealing with Eigen

### LINKED ISSUE #143: Angle values don't get wrapped
### Summary

The angle values for object states don't get wrapped during the covariance intersection fusion and unscented Kalman filter predict steps, causing numerical errors. This isn't an issue when dealing with the `CtrvState` and `CtraState` classes because the `yaw` fields use the `Angle` class. However, the problematic functions convert the state values into `Eigen::Matrix` instances, which don't have wrapping.

### Commit

`develop`

### Expected Behavior

The angle values get wrapped when doing covariance intersection fusing or Kalman filter predictions.

### Actual Behavior

The angle values don't get wrapped.

### Steps to Reproduce the Actual Behavior

1. Inspect code

### Related Work

_No response_

### PR DESCRIPTION
**Pull request by adamlm**
# PR Details
## Description

This PR fixes a bug that caused numerical issues when doing covariance intersection or unscented Kalman filter predictions. When CTRV and CTRA state vectors get converted to `Eigen::Matrix` types, they lose the auto-wrap feature for angle values. We have to manually wrap them to avoid numerical issues.

> [!NOTE]
> These changes will affect the tracking library's performance for general cases. We are changing the implementation to support a specific use case. We will revisit a more robust fix in the future when time allows.

## Related GitHub Issue

Closes #143

## Related Jira Key

Closes [CDAR-716](https://usdot-carma.atlassian.net/browse/CDAR-716)

## Motivation and Context

Bug fix

## How Has This Been Tested?

Manually in downstream packages.

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [x] All new and existing tests passed.

[CDAR-716]: https://usdot-carma.atlassian.net/browse/CDAR-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: include/multiple_object_tracking/unscented_kalman_filter.hpp [hunk 1]
```diff
@@ -74,8 +74,17 @@ inline auto unscented_kalman_filter_predict(
   }
 
   // Convert mean and sigma points into Eigen::MatrixXf
-  const auto m_sigma_points{
-    mean_and_sigma_pints_to_matrix_xf(predicted_mean, predicted_sigma_points)};
+  auto m_sigma_points{mean_and_sigma_pints_to_matrix_xf(predicted_mean, predicted_sigma_points)};
```
Comment (MishkaMN) [inline include/multiple_object_tracking/unscented_kalman_filter.hpp:77]: mean_and_sigma_pints_to_matrix_xf

has a typo. Can we fix it while we are at it? (says pints instead of points). Will there be any case where the angle is more than -360 degrees?

**Review by MishkaMN — CHANGES_REQUESTED** [review]

File: include/multiple_object_tracking/unscented_kalman_filter.hpp (hunk 1 above)
Comment (adamlm) [reply include/multiple_object_tracking/unscented_kalman_filter.hpp]: No because the vectors get generated from classes with auto-wrapping angles.

**Review by MishkaMN — APPROVED** [review]
